src/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from django.contrib import admin
from products.views import IndexView

from django.urls import include, path, re_path

static_urlpatterns = [
    re_path(r"^media/(?P<path>.*)$", serve, {"document_root": settings.MEDIA_ROOT}),
    re_path(r"^static/(?P<path>.*)$", serve, {"document_root": settings.STATIC_ROOT}),
]

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('check-task-status/', IndexView.as_view(), name='check_task_status'),
    path('translater/', include('products.urls', namespace='translater')),
    path('users/', include('users.urls', namespace='users')),
    path('support/', include('support.urls', namespace='support')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if not settings.TESTING:
    urlpatterns += path("__debug__/", include("debug_toolbar.urls")),

src/support/urls.py
from support.views import (SupportPageView, SendMessageView, ModeratorDashboardView)
from django.urls import path


app_name = 'support'

urlpatterns = [
    path('', SupportPageView.as_view(), name='support_page'),
    path('<int:session_id>/', SupportPageView.as_view(), name='session'),
    path('send-message/', SendMessageView.as_view(), name='send_message'),
    path('moderator-dashboard/', ModeratorDashboardView.as_view(), name='moderator_dashboard'),
]

src/users/urls.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LogoutView
from django.urls import path

from users.views import (UserLoginView, UserRegistrationView, UserProfileView, ResetPasswordView,
                         EmailVerificationView, )

app_name = 'users'

urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('registration/', UserRegistrationView.as_view(), name='registration'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('verify/<str:email>/<uuid:code>/', EmailVerificationView.as_view(), name='email_verification'),
    path('profile/<int:pk>/', login_required(UserProfileView.as_view()), name='profile'),
    path('password-reset/', ResetPasswordView.as_view(), name='password_reset'),
]

src/users/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser, Group, Permission
from django.core.mail import send_mail
from django.db import models
from django.urls import reverse
from django.utils.timezone import now


class SexOptions(models.TextChoices):
    UNSURE = 'U', 'Не выбрано'
    FEMALE = 'F', 'Женщина'
    MALE = 'M', 'Мужчина'


class User(AbstractUser):
    is_verified_email = models.BooleanField(default=False)
    email = models.EmailField(unique=True, blank=False)
    sex = models.CharField(max_length=1, choices=SexOptions.choices)
    age = models.PositiveIntegerField(null=True, blank=True)

    groups = models.ManyToManyField(
        Group,
        related_name="custom_user_set",
        blank=True,
        help_text="The groups this user belongs to.",
        verbose_name="groups",
    )
    user_permissions = models.ManyToManyField(
        Permission,
        related_name="custom_user_set_permissions",
        blank=True,
        help_text="Specific permissions for this user.",
        verbose_name="user permissions",
    )

    def __str__(self):
        return self.email


class EmailVerification(models.Model):
    code = models.UUIDField(unique=True)
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    expiration = models.DateTimeField()

    def __str__(self):
        return f'EmailVerification object for {self.user.email}'

    def send_verification_email(self):
        link = reverse('users:email_verification', kwargs={'email': self.user.email, 'code': self.code})
        verification_link = f'{settings.DOMAIN_NAME}{link}'
        subject = f'Подтверждение электронной почты для {self.user.username}'
        message = (
            f'Для подтверждения учётной записи для {self.user.username} перейдите по ссылке:'
            f' {verification_link}')
        send_mail(
            subject=subject,
            message=message,
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[self.user.email],
            fail_silently=False,
        )

    def is_expired(self):
        return now() >= self.expiration

src/users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm

from users.models import User, SexOptions
from users.tasks import send_email_verification


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': "form-control form-control-lg shadow-sm",
        'placeholder': "Введите имя пользователя"}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control form-control-lg shadow-sm',
        'placeholder': "Введите пароль"}))

    class Meta:
        model = User


class UserRegistrationForm(UserCreationForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control form-control-lg shadow-sm',
        'placeholder': "Имя",
        'max_length': 20}))
    # last_name = forms.CharField(widget=forms.TextInput(attrs={
    #     'class': 'form-control form-control-lg shadow-sm',
    #     'placeholder': "Фамилия"}))
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': "form-control form-control-lg shadow-sm",
        'placeholder': "Логин",
        'max_length': 20}))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'class': 'form-control form-control-lg shadow-sm',
        'placeholder': "Адрес эл. почты"}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control form-control-lg shadow-sm',
        'placeholder': "Пароль"}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control form-control-lg shadow-sm',
        'placeholder': "Подтвердите пароль"}))

    class Meta:
        model = User
        fields = ('first_name', 'username', 'email', 'password1', 'password2')

    def save(self, commit=True):
        user = super(UserRegistrationForm, self).save(commit=True)
        # Вызов прямой отправки письма вместо Celery задачи
        send_email_verification(user.id)
        return user


class UserProfileForm(UserChangeForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'readonly': True}))
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control', 'readonly': True}))
    sex = forms.ChoiceField(
        choices=SexOptions.choices,
        widget=forms.Select(attrs={
            'class': 'form-control',
            'placeholder': "Выберите пол"}))
    age = forms.IntegerField(
        widget=forms.NumberInput(attrs={
            'class': 'form-control',
            'placeholder': "Укажите ваш возраст"}))

    class Meta:
        model = User
        fields = ('username', 'first_name', 'email', 'sex', 'age')

src/users/views.py
from django.contrib.auth.views import LoginView, PasswordResetView
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import HttpResponseRedirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView
from django.views.generic.base import TemplateView

from users.forms import UserLoginForm, UserRegistrationForm, UserProfileForm
from users.models import User, EmailVerification


class UserLoginView(LoginView):
    template_name = 'users/login.html'
    form_class = UserLoginForm
    success_url = reverse_lazy('index')
    title = 'Авторизация'


class UserRegistrationView(SuccessMessageMixin, CreateView):
    model = User
    form_class = UserRegistrationForm
    template_name = 'users/registration.html'
    success_url = reverse_lazy('users:login')
    success_message = 'Вы успешно зарегистрированы!'
    title = 'Регистрация'


class UserProfileView(UpdateView):
    model = User
    template_name = 'users/profile.html'
    form_class = UserProfileForm
    title = 'Профиль'

    def get_success_url(self):
        return reverse_lazy('users:profile', args=[self.object.id])


class EmailVerificationView(TemplateView):
    title = 'Подтверждение почты'
    template_name = 'users/password/email_verification.html'

    def get(self, request, *args, **kwargs):
        code = kwargs['code']
        user = User.objects.get(email=kwargs['email'])
        email_verifications = EmailVerification.objects.filter(user=user, code=code)
        if email_verifications.exists() and not email_verifications.first().is_expired():
            user.is_verified_email = True
            user.save()
            return super(EmailVerificationView, self).get(request, *args, **kwargs)
        else:
            return HttpResponseRedirect(reverse('index'))


class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    template_name = 'users/password/password_reset.html'
    email_template_name = 'users/password/password_reset_email.html'
    subject_template_name = 'users/password/password_reset_subject.txt'
    success_message = ("Мы отправили вам по электронной почте инструкции по установке пароля, если существует учетная"
                       " запись с указанным вами адресом электронной почты. Вы должны получить их в ближайшее время."
                       " Если вы не получили электронное письмо, Пожалуйста, убедитесь, что вы правильно ввели адрес,"
                       " под которым зарегистрировались, и проверьте папку со спамом.")
    success_url = reverse_lazy('users:login')

src/users/templates/users/password/email_verification.html
{% extends 'layouts/base.html' %}

{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-5">
                <div class="card shadow-lg border-0 rounded-lg mt-5">
                    <div class="card-header"><h3 class="text-center font-weight-light my-4">Поздравляем</h3>
                    </div>
                    <div class="card-body text-center">
                        <h4>Ваша учетная запись успешно подтверждена!</h4>
                    </div>
                    <div class="card-footer text-center">
                        <div class="small"><a href="{% url 'users:login' %}">Продолжить</a></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

src/users/templates/users/password/password_reset.html
{% extends "layouts/base.html" %}
{% block content %}
    <div class="form-content my-3 p-3">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-6"> <!-- Увеличено с col-lg-5 до col-lg-6 -->
                    <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">
                        <div class="card-header text-center bg-green">
                            <div id="error_div"></div>
                            <h3 class="font-weight-light my-4">Забыли пароль?</h3>
                        </div>

                        {% if form.errors %}
                            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                <div id="form_errors">
                                    {% for key, value in form.errors.items %}
                                        <strong>{{ value }}</strong>
                                    {% endfor %}
                                </div>
                                <button type="button" class="btn-close" data-bs-dismiss="alert"
                                        aria-label="Close"></button>
                            </div>
                        {% endif %}

                        <div class="card-body">
                            <form method="POST">
                                {% csrf_token %}
                                <div class="form-group mb-3">
                                    <label class="small mb-1" for="id_email"></label>
                                    <input type="email" name="email" class="form-control"
                                           autocomplete="email" maxlength="254" required id="id_email"
                                           placeholder="Введите адрес эл. почты">
                                </div>
                                <div class="d-grid">
                                    <button type="submit" class="btn btn-dark">Подтвердить</button>
                                </div>
                            </form>
                        </div>

                        <div class="card-footer text-center">
                            <div class="small">
                                <!-- Добавлен класс text-primary для яркости и немного увеличен шрифт -->
                                <a href="{% url 'users:registration' %}" class="text-primary fw-bold"
                                   style="font-size: 1.1em;">Создать новый аккаунт</a><br><br>
                                <a href="{% url 'users:login' %}" class="text-primary fw-bold"
                                   style="font-size: 1.1em;">Вернуться к странице авторизации</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

src/users/templates/users/password/password_reset_complete.html
{% extends 'layouts/base.html' %}
{% block content %}
<div class="container my-3 p-3">
    <div class="row justify-content-center">
        <div class="col-lg-5">
            <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">
                <div class="card-body">
                    <div class="text-center mb-4">
                        <i class="fas fa-check-circle text-success" style="font-size: 3rem;"></i>
                    </div>
                    <h2 class="card-title text-center">Пароль успешно изменён!</h2>
                    <div class="alert alert-info text-center mt-3">
                        <p>Ваш пароль был успешно изменён. Вы теперь можете войти в свою учётную запись, используя новый пароль.</p>
                        <a href="{% url 'users:login' %}" class="btn btn-primary">Войти</a>
                    </div>
{#                    <div class="text-center mt-4">#}
{#                        <p>Возникли проблемы? <a href="{% url 'users:support' %}">Свяжитесь с поддержкой</a></p>#}
{#                        <p><a href="{% url 'users:faq' %}">Часто задаваемые вопросы</a></p>#}
{#                    </div>#}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

src/users/templates/users/password/password_reset_confirm.html
{% extends 'layouts/base.html' %}
{% block title %} Восстановление пароля {% endblock title %}
{% block content %}
    <div class="form-content my-3 p-3">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-5">
                    {% if validlink %}
                        <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">
                            <div class="card-header justify-content-center">
                                <h3 class="font-weight-light my-4 text-center">Сбросить пароль</h3>
                            </div>
                            {% if form.errors %}
                                <div class="alert alert-danger alert-dismissible" role="alert">
                                    <div id="form_errors">
                                        {% for key, value in form.errors.items %}
                                            <strong>{{ value }}</strong>
                                        {% endfor %}
                                    </div>
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                            {% endif %}

                            <div class="card-body">
                                <form method="POST">
                                    {% csrf_token %}
                                    <div class="form-row">
                                        <div class="col-md-10 offset-md-1">
                                            <div class="form-group">
                                                <label class="small mb-1" for="id_new_password1">Новый пароль</label>
                                                <input type="password" name="new_password1" autocomplete="new-password"
                                                       class="form-control" required id="id_new_password1"
                                                       placeholder="Enter password"/>
                                                <span>
                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="col-md-10 offset-md-1">
                                            <div class="form-group">
                                                <label class="small mb-1" for="id_new_password2">Подтверждение нового пароля</label>
                                                <input type="password" name="new_password2" autocomplete="new-password"
                                                       required id="id_new_password2" class="form-control"
                                                       placeholder="Confirm password"/>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="col-md-10 offset-md-1">
                                            <div class="form-group mt-0 mb-1">
                                                <button type="submit" class="col-md-12 btn btn-dark" id="reset">Восстановление пароля
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    {% else %}
                        <div class="alert alert-warning">
                            Ссылка для сброса пароля недействительна, возможно, потому, что она уже использовалась.
                            Пожалуйста, запросите сброс нового пароля.
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

src/users/templates/users/password/password_reset_email.html
{% load i18n %}{% autoescape off %}
    {% blocktranslate %}Вы получили это электронное письмо, поскольку запросили сброс пароля для своей учетной записи на сайте
        {{ site_name }}.{% endblocktranslate %}
{#     You're receiving this email because you requested a password reset for your user account at#}

    {% translate "Please go to the following page and choose a new password:" %}
    {% block reset_link %}
        {{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
    {% endblock %}
    {% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

    {% translate "Thanks for using our site!" %}

    {% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}