src/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from django.contrib import admin
from products.views import IndexView

from django.urls import include, path, re_path

static_urlpatterns = [
    re_path(r"^media/(?P<path>.*)$", serve, {"document_root": settings.MEDIA_ROOT}),
    re_path(r"^static/(?P<path>.*)$", serve, {"document_root": settings.STATIC_ROOT}),
]

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('check-task-status/', IndexView.as_view(), name='check_task_status'),
    path('translater/', include('products.urls', namespace='translater')),
    path('users/', include('users.urls', namespace='users')),
    path('support/', include('support.urls', namespace='support')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if not settings.TESTING:
    urlpatterns += path("__debug__/", include("debug_toolbar.urls")),

src/users/urls.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LogoutView
from django.urls import path

from users.views import (UserLoginView, UserRegistrationView, UserProfileView, ResetPasswordView,
                         EmailVerificationView, )

app_name = 'users'

urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('registration/', UserRegistrationView.as_view(), name='registration'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('verify/<str:email>/<uuid:code>/', EmailVerificationView.as_view(), name='email_verification'),
    path('profile/<int:pk>/', login_required(UserProfileView.as_view()), name='profile'),
    path('password-reset/', ResetPasswordView.as_view(), name='password_reset'),
]

src/users/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser, Group, Permission
from django.core.mail import send_mail
from django.db import models
from django.urls import reverse
from django.utils.timezone import now


class SexOptions(models.TextChoices):
    UNSURE = 'U', 'Не выбрано'
    FEMALE = 'F', 'Женщина'
    MALE = 'M', 'Мужчина'


class User(AbstractUser):
    is_verified_email = models.BooleanField(default=False)
    email = models.EmailField(unique=True, blank=False)
    sex = models.CharField(max_length=1, choices=SexOptions.choices)
    age = models.PositiveIntegerField(null=True, blank=True)

    groups = models.ManyToManyField(
        Group,
        related_name="custom_user_set",
        blank=True,
        help_text="The groups this user belongs to.",
        verbose_name="groups",
    )
    user_permissions = models.ManyToManyField(
        Permission,
        related_name="custom_user_set_permissions",
        blank=True,
        help_text="Specific permissions for this user.",
        verbose_name="user permissions",
    )

    def __str__(self):
        return self.email


class EmailVerification(models.Model):
    code = models.UUIDField(unique=True)
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    expiration = models.DateTimeField()

    def __str__(self):
        return f'EmailVerification object for {self.user.email}'

    def send_verification_email(self):
        link = reverse('users:email_verification', kwargs={'email': self.user.email, 'code': self.code})
        verification_link = f'{settings.DOMAIN_NAME}{link}'
        subject = f'Подтверждение электронной почты для {self.user.username}'
        message = (
            f'Для подтверждения учётной записи для {self.user.username} перейдите по ссылке:'
            f' {verification_link}')
        send_mail(
            subject=subject,
            message=message,
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[self.user.email],
            fail_silently=False,
        )

    def is_expired(self):
        return now() >= self.expiration

src/users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm

from users.models import User, SexOptions
from users.tasks import send_email_verification


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': "form-control form-control-lg shadow-sm",
        'placeholder': "Введите имя пользователя"}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control form-control-lg shadow-sm',
        'placeholder': "Введите пароль"}))

    class Meta:
        model = User


class UserRegistrationForm(UserCreationForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control form-control-lg shadow-sm',
        'placeholder': "Имя",
        'max_length': 20}))
    # last_name = forms.CharField(widget=forms.TextInput(attrs={
    #     'class': 'form-control form-control-lg shadow-sm',
    #     'placeholder': "Фамилия"}))
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': "form-control form-control-lg shadow-sm",
        'placeholder': "Логин",
        'max_length': 20}))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'class': 'form-control form-control-lg shadow-sm',
        'placeholder': "Адрес эл. почты"}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control form-control-lg shadow-sm',
        'placeholder': "Пароль"}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control form-control-lg shadow-sm',
        'placeholder': "Подтвердите пароль"}))

    class Meta:
        model = User
        fields = ('first_name', 'username', 'email', 'password1', 'password2')

    def save(self, commit=True):
        user = super(UserRegistrationForm, self).save(commit=True)
        # Вызов прямой отправки письма вместо Celery задачи
        send_email_verification(user.id)
        return user


class UserProfileForm(UserChangeForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'readonly': True}))
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control', 'readonly': True}))
    sex = forms.ChoiceField(
        choices=SexOptions.choices,
        widget=forms.Select(attrs={
            'class': 'form-control',
            'placeholder': "Выберите пол"}))
    age = forms.IntegerField(
        widget=forms.NumberInput(attrs={
            'class': 'form-control',
            'placeholder': "Укажите ваш возраст"}))

    class Meta:
        model = User
        fields = ('username', 'first_name', 'email', 'sex', 'age')

src/users/views.py
from django.contrib.auth.views import LoginView, PasswordResetView
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import HttpResponseRedirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView
from django.views.generic.base import TemplateView

from users.forms import UserLoginForm, UserRegistrationForm, UserProfileForm
from users.models import User, EmailVerification


class UserLoginView(LoginView):
    template_name = 'users/login.html'
    form_class = UserLoginForm
    success_url = reverse_lazy('index')
    title = 'Авторизация'


class UserRegistrationView(SuccessMessageMixin, CreateView):
    model = User
    form_class = UserRegistrationForm
    template_name = 'users/registration.html'
    success_url = reverse_lazy('users:login')
    success_message = 'Вы успешно зарегистрированы!'
    title = 'Регистрация'


class UserProfileView(UpdateView):
    model = User
    template_name = 'users/profile.html'
    form_class = UserProfileForm
    title = 'Профиль'

    def get_success_url(self):
        return reverse_lazy('users:profile', args=[self.object.id])


class EmailVerificationView(TemplateView):
    title = 'Подтверждение почты'
    template_name = 'users/password/email_verification.html'

    def get(self, request, *args, **kwargs):
        code = kwargs['code']
        user = User.objects.get(email=kwargs['email'])
        email_verifications = EmailVerification.objects.filter(user=user, code=code)
        if email_verifications.exists() and not email_verifications.first().is_expired():
            user.is_verified_email = True
            user.save()
            return super(EmailVerificationView, self).get(request, *args, **kwargs)
        else:
            return HttpResponseRedirect(reverse('index'))


class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    template_name = 'users/password/password_reset.html'
    email_template_name = 'users/password/password_reset_email.html'
    subject_template_name = 'users/password/password_reset_subject.txt'
    success_message = ("Мы отправили вам по электронной почте инструкции по установке пароля, если существует учетная"
                       " запись с указанным вами адресом электронной почты. Вы должны получить их в ближайшее время."
                       " Если вы не получили электронное письмо, Пожалуйста, убедитесь, что вы правильно ввели адрес,"
                       " под которым зарегистрировались, и проверьте папку со спамом.")
    success_url = reverse_lazy('users:login')

src/users/templates/users/login.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
{% endblock %}
{% block content %}
    <main>
        <div class="container py-5 d-flex justify-content-center align-items-center" style="min-height: 80vh;">
            <div class="col-md-6 col-lg-5">
                {% if messages or form.non_field_errors %}
                    <div class="alert {% if messages %} alert-success {% else %} alert-warning {% endif %} alert-dismissible fade show mt-5 shadow"
                         role="alert">
                        {% if messages %}
                            {% for message in messages %}
                                {{ message }}
                            {% endfor %}
                        {% else %}
                            {{ form.non_field_errors }}
                        {% endif %}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% endif %}

                <div class="card border-0 shadow-lg rounded-3 mt-5">
                    <div class="card-header text-center py-4 bg-primary text-white">
                        <h3 class="fw-bold mb-0">Авторизация</h3>
                    </div>
                    <div class="card-body p-4">
                        <form action="{% url 'users:login' %}" method="post">
                            {% csrf_token %}
                            <div class="mb-3">
                                <label for="{{ form.username.id_for_label }}"
                                       class="form-label small text-muted"></label>
                                {{ form.username }}
                            </div>
                            <div class="mb-3 position-relative">
                                <label for="{{ form.password.id_for_label }}"
                                       class="form-label small text-muted"></label>
                                {{ form.password }}
                                <span class="position-absolute top-50 end-0 me-3" style="cursor: pointer;"
                                      onclick="togglePasswordVisibility('id_password', 'togglePasswordIcon')">
                                    <i class="fa fa-eye" id="togglePasswordIcon"></i>
                                </span>
                            </div>

                            <div class="d-flex justify-content-between align-items-center mt-4">
                                <a class="small text-decoration-none" href="{% url 'users:password_reset' %}">Забыли
                                    пароль?</a>
                                <button class="btn btn-primary btn-lg rounded-pill px-4 shadow" type="submit">Войти
                                </button>
                            </div>
                        </form>
                    </div>
                    <div class="card-footer text-center bg-light py-3">
                        <p class="small mb-0"><a href="{% url 'users:registration' %}" class="text-primary fw-bold">Нужен
                            аккаунт? Зарегистрируйтесь!</a></p>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

{% block scripts %}
    <script src="{% static 'js/authorization.js' %}"></script>
{% endblock %}

src/users/templates/users/profile.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block content %}
    <div class="container py-4">
        <div class="row">
            <div class="col-lg-8 mx-auto">
                <h2 class="text-center mb-4">Профиль</h2>
                <div class="card shadow-sm p-4">
                    <form action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="row g-3">
                            <div class="col-md-4">
                                <label for="{{ form.first_name.id_for_label }}" class="form-label">Имя</label>
                                {{ form.first_name }}
                            </div>
                            <div class="col-md-4">
                                <label for="{{ form.sex.id_for_label }}" class="form-label">Пол</label>
                                {{ form.sex }}
                            </div>
                            <div class="col-md-4">
                                <label for="{{ form.age.id_for_label }}" class="form-label">Возраст</label>
                                {{ form.age }}
                            </div>
                        </div>
                        <div class="row g-3 mt-3">
                            <div class="col-md-6">
                                <label for="{{ form.username.id_for_label }}" class="form-label">Имя
                                    пользователя</label>
                                {{ form.username }}
                            </div>
                            <div class="col-md-6">
                                <label for="{{ form.email.id_for_label }}" class="form-label">Адрес электронной
                                    почты</label>
                                {{ form.email }}
                            </div>
                        </div>
                        <div class="d-grid gap-2 mt-4">
                            <button type="submit" class="btn btn-primary btn-sm btn-block">Сохранить</button>
                        </div>
                    </form>
                </div>


                <!-- Раздел подписки -->
                <div id="subscriptionSection" class="card shadow-sm p-4 mt-4">
                    <h3 class="mb-3">Подписка</h3>
                    <p class="text-muted">С подпиской вы можете использовать сервис без ограничений. Без подписки вы
                        ограничены одним переводом букета в месяц.</p>
                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" id="subscribeCheck">
                        <label class="form-check-label" for="subscribeCheck">
                            Подписаться на премиум план
                        </label>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

src/users/templates/users/registration.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
{% endblock %}
{% block content %}
    <main>
        <div class="container py-5 d-flex justify-content-center align-items-center" style="min-height: 80vh;">
            <div class="col-md-7 col-lg-6">
                {% if form.errors %}
                    <div class="alert alert-warning alert-dismissible fade show shadow-sm mt-5" role="alert">
                        {{ form.errors }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% endif %}

                <div class="card border-0 shadow-lg rounded-3 mt-5">
                    <div class="card-header text-center py-4 bg-primary text-white">
                        <h3 class="fw-bold mb-0">Создать аккаунт</h3>
                    </div>
                    <div class="card-body p-4">
                        <form action="{% url 'users:registration' %}" method="post">
                            {% csrf_token %}
                            <div class="row mb-3">
                                <div class="col-md-6">
                                    <label for="{{ form.first_name.id_for_label }}"
                                           class="form-label small text-muted"></label>
                                    {{ form.first_name }}
                                </div>
                                <div class="col-md-6">
                                    <label for="{{ form.username.id_for_label }}"
                                           class="form-label small text-muted"></label>
                                    {{ form.username }}
                                </div>
                            </div>
                            <div class="row mb-3">
                                <div class="col-md-12">
                                    <label for="{{ form.email.id_for_label }}"
                                           class="form-label small text-muted"></label>
                                    {{ form.email }}
                                </div>

                            </div>
                            <div class="row">
                                <div class="col-md-6 mb-3 position-relative">
                                    <label for="{{ form.password1.id_for_label }}"
                                           class="form-label small text-muted"></label>
                                    {{ form.password1 }}
                                    <span class="position-absolute top-50 end-0 me-4" style="cursor: pointer;"
                                          onclick="togglePasswordVisibility('id_password1', 'togglePasswordIcon1')">
                                        <i class="fa fa-eye" id="togglePasswordIcon1"></i>
                                    </span>
                                </div>
                                <div class="col-md-6 mb-3 position-relative">
                                    <label for="{{ form.password2.id_for_label }}"
                                           class="form-label small text-muted"></label>
                                    {{ form.password2 }}
                                    <span class="position-absolute top-50 end-0 me-4" style="cursor: pointer;"
                                          onclick="togglePasswordVisibility('id_password2', 'togglePasswordIcon2')">
                                        <i class="fa fa-eye" id="togglePasswordIcon2"></i>
                                    </span>
                                </div>
                            </div>


                            <button class="btn btn-primary btn-lg w-100 rounded-pill shadow mt-4" type="submit">Создать
                                аккаунт
                            </button>
                        </form>
                    </div>
                    <div class="card-footer text-center bg-light py-3">
                        <p class="small mb-0"><a href="{% url 'users:login' %}" class="text-primary fw-bold">Уже есть
                            аккаунт? Авторизоваться</a></p>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

{% block scripts %}
    <script src="{% static 'js/authorization.js' %}"></script>
{% endblock %}