src/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from django.contrib import admin
from products.views import IndexView

from django.urls import include, path, re_path

static_urlpatterns = [
    re_path(r"^media/(?P<path>.*)$", serve, {"document_root": settings.MEDIA_ROOT}),
    re_path(r"^static/(?P<path>.*)$", serve, {"document_root": settings.STATIC_ROOT}),
]

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('check-task-status/', IndexView.as_view(), name='check_task_status'),
    path('translater/', include('products.urls', namespace='translater')),
    path('users/', include('users.urls', namespace='users')),
    path('support/', include('support.urls', namespace='support')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if not settings.TESTING:
    urlpatterns += path("__debug__/", include("debug_toolbar.urls")),

src/support/urls.py
from support.views import (SupportPageView, SendMessageView, ModeratorDashboardView)
from django.urls import path


app_name = 'support'

urlpatterns = [
    path('', SupportPageView.as_view(), name='support_page'),
    path('<int:session_id>/', SupportPageView.as_view(), name='session'),
    path('send-message/', SendMessageView.as_view(), name='send_message'),
    path('moderator-dashboard/', ModeratorDashboardView.as_view(), name='moderator_dashboard'),
]

src/users/urls.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LogoutView
from django.urls import path

from users.views import (UserLoginView, UserRegistrationView, UserProfileView, ResetPasswordView,
                         EmailVerificationView, )

app_name = 'users'

urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('registration/', UserRegistrationView.as_view(), name='registration'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('verify/<str:email>/<uuid:code>/', EmailVerificationView.as_view(), name='email_verification'),
    path('profile/<int:pk>/', login_required(UserProfileView.as_view()), name='profile'),
    path('password-reset/', ResetPasswordView.as_view(), name='password_reset'),
]

src/templates/layouts/auth_base.html
{% load static %}


<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>FloriAI</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"/>
    {% block css %} {% endblock %}

</head>
<body>


{% block content %} {% endblock %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
{% block scripts %} {% endblock %}
</body>
</html>

src/templates/layouts/base.html
{% load static %}


<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>FloriAI</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/fonts.css' %}"/>

    <link rel="icon" type="image/png" href="{% static 'icon/favicon-96x96.png' %}" sizes="96x96"/>
    <link rel="icon" type="image/svg+xml" href="{% static 'icon/favicon.svg' %}"/>
    <link rel="shortcut icon" href="{% static 'icon/favicon.ico' %}"/>
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'icon/apple-touch-icon.png' %}"/>
    <meta name="apple-mobile-web-app-title" content="FloriAI"/>
    <link rel="manifest" href="{% static 'icon/site.webmanifest' %}"/>
    {% block css %} {% endblock %}

</head>
<body>
<header>
    <nav class="navbar navbar-expand-lg navbar-light">
        <a class="navbar-brand mx-3 d-flex align-items-center" href="{% url 'index' %}">
            <img src="{% static 'img/ProjIcon.png' %}" alt="FloriAI Icon" width="140">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Переключить навигацию">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav me-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'translater:index' %}">Перевести</a>
                </li>
                {% if not user.is_staff %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'support:support_page' %}">Чат поддержки</a>
                    </li>
                {% endif %}
            </ul>
            {% if not user.is_authenticated %}
                <ul class="navbar-nav ms-auto me-3">
                    <li class="nav-item me-3">
                        <a class="nav-link" href="{% url 'users:login' %}">Войти</a>
                    </li>
                </ul>
            {% else %}
                {% if user.is_staff %}
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'admin:index' %}">Админ-панель</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'support:moderator_dashboard' %}">Чат поддержки
                                (модерация)</a>
                        </li>
                    </ul>
                {% endif %}
                <ul class="navbar-nav me-3">
                    <li class="nav-item">
                        <span>Здравствуйте, {{ user.first_name }}!</span>
                    </li>
                </ul>                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:profile' user.id %}">Профиль</a>
                    </li>
                </ul>
                <ul class="navbar-nav me-3">
                    <li class="nav-item">
                        <form action="{% url 'users:logout' %}" method="post" style="display:inline;">
                            {% csrf_token %}
                            <button type="submit" class="nav-link btn-no-style">Выйти</button>
                        </form>
                    </li>
                </ul>
            {% endif %}
        </div>
    </nav>
</header>



{% block content %} {% endblock %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
{% block scripts %} {% endblock %}
</body>
</html>