src/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from django.contrib import admin
from products.views import IndexView

from django.urls import include, path, re_path

static_urlpatterns = [
    re_path(r"^media/(?P<path>.*)$", serve, {"document_root": settings.MEDIA_ROOT}),
    re_path(r"^static/(?P<path>.*)$", serve, {"document_root": settings.STATIC_ROOT}),
]

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('check-task-status/', IndexView.as_view(), name='check_task_status'),
    path('translater/', include('products.urls', namespace='translater')),
    path('users/', include('users.urls', namespace='users')),
    path('support/', include('support.urls', namespace='support')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if not settings.TESTING:
    urlpatterns += path("__debug__/", include("debug_toolbar.urls")),

src/support/urls.py
from support.views import (SupportPageView, SendMessageView, ModeratorDashboardView)
from django.urls import path


app_name = 'support'

urlpatterns = [
    path('', SupportPageView.as_view(), name='support_page'),
    path('<int:session_id>/', SupportPageView.as_view(), name='session'),
    path('send-message/', SendMessageView.as_view(), name='send_message'),
    path('moderator-dashboard/', ModeratorDashboardView.as_view(), name='moderator_dashboard'),
]

src/users/urls.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LogoutView
from django.urls import path

from users.views import (UserLoginView, UserRegistrationView, UserProfileView, ResetPasswordView,
                         EmailVerificationView, )

app_name = 'users'

urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('registration/', UserRegistrationView.as_view(), name='registration'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('verify/<str:email>/<uuid:code>/', EmailVerificationView.as_view(), name='email_verification'),
    path('profile/<int:pk>/', login_required(UserProfileView.as_view()), name='profile'),
    path('password-reset/', ResetPasswordView.as_view(), name='password_reset'),
]

src/support/models.py
from django.db import models
from users.models import User


class ChatSupportSession(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Session for {self.user}"


class ChatSupportMessage(models.Model):
    session = models.ForeignKey(ChatSupportSession, on_delete=models.CASCADE, related_name='messages')
    sender = models.CharField(max_length=30)
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Message from {self.sender} at {self.timestamp}"

src/support/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.http import JsonResponse
from django.views.generic.base import TemplateView
from rest_framework.views import APIView
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect

from support.models import ChatSupportMessage, ChatSupportSession


class SupportPageView(LoginRequiredMixin, TemplateView):
    template_name = 'support/support_page.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_staff:
            session_id = self.kwargs.get('session_id')
            session = get_object_or_404(ChatSupportSession, id=session_id)
        else:
            session = ChatSupportSession.objects.filter(user=self.request.user).first()
        context["session"] = session
        context["messages"] = session.messages.order_by("timestamp") if session else []
        return context


class SendMessageView(LoginRequiredMixin, APIView):
    def post(self, request, *args, **kwargs):
        try:
            content = request.data.get('content')
            sender = "Модератор" if request.user.is_staff else request.user.first_name.title()
            if request.user.is_staff:
                session_id = request.data.get('session_id')
                if not session_id:
                    return JsonResponse({"error": "Не указан ID сессии."}, status=400)
                session = ChatSupportSession.objects.filter(id=session_id).first()
            else:
                session, created = ChatSupportSession.objects.get_or_create(user=request.user)

            message = ChatSupportMessage.objects.create(
                session=session,
                sender=sender,
                content=content,
            )

            # Перенаправление обратно на страницу чата
            return redirect('support:support_page')
        except ChatSupportSession.DoesNotExist:
            return JsonResponse({"error": "Сессия не найдена."}, status=400)
        except Exception as e:
            return JsonResponse({"error": str(e)}, status=400)


class ModeratorDashboardView(LoginRequiredMixin, UserPassesTestMixin, TemplateView):
    template_name = 'support/support_page_for_moderator.html'

    def test_func(self):
        return self.request.user.is_staff

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        sessions = ChatSupportSession.objects.all().order_by("created_at")
        context["sessions"] = sessions
        return context

src/support/templates/support/support_page.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block content %}
    <div class="container mt-4">
        <h1 class="pb-3 text-center">Чат с техподдержкой</h1>

        <div class="chat-box p-3 mb-3 bg-white">
            {% if session %}
                {% for message in messages %}
                    <div class="message mb-2">
                        <strong>{{ message.sender|title }}:</strong>
                        <span>{{ message.content }}</span>
                        <small class="text-muted">{{ message.timestamp }}</small>
                    </div>
                    {% empty %}
                    <p>Сообщений пока нет. Начните общение!</p>
                {% endfor %}
            {% else %}
                <p>Сессия ещё не начата. Отправьте сообщение, чтобы начать.</p>
            {% endif %}
        </div>

        <form method="POST" id="messageForm" class="d-flex pb-5" action="{% url 'support:send_message' %}">
            {% csrf_token %}
            <input type="hidden" name="session_id" value="{% if session %}{{ session.id }}{% endif %}">
            <textarea id="messageContent" name="content" class="form-control me-2" placeholder="Введите сообщение"
                      required rows="3" oninput="autoResize(this)"></textarea>
            <button type="submit" class="btn btn-primary">Отправить</button>
        </form>


        <div id="statusMessage" class="mt-2"></div>

        <!-- Добавляем скрытые элементы для session_id и user_username -->
        <div id="session_id" style="display: none;">{{ session.id }}</div>
        <div id="user_username" style="display: none;">{{ user.username }}</div>
    </div>
{% endblock %}

{% block scripts %}
    <script src="{% static 'js/chat_support.js' %}"></script>
{% endblock %}

src/support/templates/support/support_page_for_moderator.html
{% extends 'layouts/base.html' %}
{% block content %}
<div class="container mt-4">
    <h1>Панель модератора</h1>
    <div class="list-group">
        {% for session in sessions %}
            <a href="{% url 'support:session' session.id %}" class="list-group-item list-group-item-action">
                Сессия ID: {{ session.id }} - {{ session.created_at }}
            </a>
        {% empty %}
            <p>Нет открытых сессий.</p>
        {% endfor %}
    </div>
</div>
{% endblock %}